### ISSUE TITLE
Flutter 3.22 release mode issue, example project is unresponsive (Critical)

### ISSUE THREAD

**Issue by shubham-gupta-16** [karvulf/flutter-reorderable-grid-view#105]
## Configuration:
Flutter Version: 3.2.2
flutter-reorderable-grid-view: 4.0.0
Running in release mode (--release)

## Behavior:
- Scrolling not working
- Dragging not working
- Item added on top of the first item  (stack)
- Item remove only changing first item

## Logs:
> Appears when I start touching the screen.
```
I/flutter (10354): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10354): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10354): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10354): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10354): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10354): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```

**Comment by karvulf** [comment]
Hi @shubham-gupta-16 
Can you try version ‘5.0.0-dev.10’ because this version will be outdated soon, there are some breaking changes so be sure to check the example app

**Comment by shubham-gupta-16** [comment]
I checked the `feature/5.0.0-release` and it is working. When you are planning to release a stable version for 5.0?

**Comment by karvulf** [comment]
I have to update the read me, then I could release it, I should find some time in two weeks, so probably in 3 weeks @shubham-gupta-16

**Comment by karvulf** [comment]
I published version `5.0.0`, so I will close this issue @shubham-gupta-16

**Comment by shubham-gupta-16** [comment]
Not fixed. Issue still exists with GridView, GridViewCount, GridViewExtent. Only GridViewBuilder working in example project.

Also, GridViewBuilder's code is not working in my project.

**Comment by karvulf** [comment]
What exactly is happening and can you show me your code how you use `ReorderableBuilder`? @shubham-gupta-16

**Comment by shubham-gupta-16** [comment]
@karvulf It's happening in example project as well. 

Here is my project: https://github.com/shubham-gupta-16/multi_image_picker_view

**Comment by karvulf** [comment]
I tried to reproduce it but everything seems to work. I will checkout your branch, maybe I can see more there. @shubham-gupta-16

**Comment by karvulf** [comment]
Is it only happening in the release mode or also in debug mode? @shubham-gupta-16

**Comment by karvulf** [comment]
I tried to start the example app on iOS in your project but I am getting the following exception when trying to install it:
```shell
[!] Unable to find a target named `RunnerTests` in project `Runner.xcodeproj`, did find `Runner`.
```
@shubham-gupta-16

**Comment by shubham-gupta-16** [comment]
@karvulf It's happening only in release mode on an Android device.

**Comment by karvulf** [comment]
So iOS works totally fine? @shubham-gupta-16 

Can you send me the output of `flutter doctor -v`? @shubham-gupta-16

**Comment by karvulf** [comment]
I tried on an emulator in release mode with your suggested branch and couldn't reproduce the issue, my flutter doctor -v output is the following:
```shell
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale de-DE)
    • Flutter version 3.19.6 on channel stable at /Users/andreborger/fvm/versions/3.19.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (vor 3 Monaten), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/andreborger/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio 2.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 78.4.2
    • Dart plugin version 233.15026.12

[✓] VS Code (version 1.91.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        
    • android-arm64  • Android 13 (API 33) (emulator)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
➜  example git:(flutter_reorderable_grid_view_5_0_0) ✗ 

```

**Comment by karvulf** [comment]
I reproduced the issue, I will try to fix it this week, thank you for finding that one! @shubham-gupta-16

**Comment by karvulf** [comment]
The issue should be fixed, can you check if it still exists? 
You can use version `5.0.1`
@shubham-gupta-16
